import './globals.css'
import { Dosis } from 'next/font/google';
import ReduxProvider from '../redux/provider'

const dosis = Dosis({subsets: ['latin'], weight: ['400']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dosis.className}><ReduxProvider>{children}</ReduxProvider></body>
    </html>
  )
}
